chore: deps husky and commitlint
hiteshchoudhary/apihub pull request #19
Opened 2023-07-19 04:20 UTC by balaji-sivasakthi

### Related issue :-
issue #16 
### Changes Made :-
- commitlint with husky config
- lint-stage config
### Additional Context :- 
 ```
[
        "ci",
        "chore",
        "docs",
        "feat",
        "fix",
        "perf",
        "refactor",
        "revert",
        "style",
        "assets"
      ]
```

2023-07-19 05:12 UTC, wajeshubham commented
@balaji-sivasakthi I appreciate your effort in keeping the project and commit messages tidy. 

However, upon testing the implementation, I discovered that the `git commit` command does not fail when an ugly commit message is provided, which ideally should happen to enforce clean commit messages. 

Also, is it expected that i run `yarn pre-commit` to lint my staged files every time before committing? 

Getting the following warning upon committing.

```
hint: The '.husky/pre-commit' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
hint: The '.husky/commit-msg' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
```
Please let me know your thoughts on this matter, and if you agree with these points. I would love to learn more about this.

2023-07-19 06:03 UTC, balaji-sivasakthi commented
@wajeshubham Thank you!  Husky will handle the pre-commit on its own, so there's no need to execute 'yarn pre-commit' before every commit. However, there might be some edge cases where we can use `yarn pre-commit` with specific options, such as `yarn pre-commit --allow-empty` to style the staged files without needing a commit message.

Sorry for the trouble, It was an egde case in mac/Linux
```
hint: The '.husky/pre-commit' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
hint: The '.husky/commit-msg' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
```
To prevent this issue, we can allow permission to the `.husky` directory by executing the following command:

```bash
chmod ug+x .husky/*
```

This command grants execute (`x`) permission to the user (`u`) and the group (`g`) for all files (`*`) inside the `.husky` directory. It ensures that the necessary scripts in the `.husky` directory can be executed properly during the pre-commit process.

```json
{
"prepare": "husky install | chmod ug+x .husky/*"
}
```

2023-07-19 13:31 UTC, wajeshubham commented
So, how about adding `yarn prepare` or `npm run prepare` in `./husky/commit-msg`? So, that we don't need to manually install the husky hooks.
```sh
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
yarn prepare # prepare husky hooks
npx --no-install commitlint --edit
```
Also, `"prepare": "husky install | chmod ug+x .husky/*"` This script works for macOS. However, just to be sure this script should not break in the windows OS.

NOTE: As this PR has changes that are involved in the contribution flow we also need to update the Contribution guide according to this new convention of commit messages.

2023-07-19 15:50 UTC, balaji-sivasakthi commented
```json 
"prepare": "husky install | chmod ug+x .husky/*"
```
Yes, this script would break on Windows. However, it can be sorted out by using cross-spawn for executing the prepare script.

```js
import { spawnSync } from 'child_process';
import os from 'os';

// Function to run commands depending on the OS
const runCommand = (command, args) => {
  const isWindows = os.platform() === 'win32';
  const shell = isWindows ? true : false;
  const commandArgs = isWindows ? ['/C', command, ...args] : [...args];

  const result = spawnSync(isWindows ? 'cmd' : command, commandArgs, {
    stdio: 'inherit',
    shell,
  });

  return result.status;
};

// Function to prepare Husky
const prepareHusky = () => {
  // Run husky install
  const huskyInstallStatus = runCommand('npx', ['husky', 'install']);

  // Set permissions for husky on macOS/Linux
  if (os.platform() !== 'win32') {
    const setPermissionsStatus = runCommand('chmod', ['+x', '.husky/*']);
    if (setPermissionsStatus !== 0) {
      console.error('Setting permissions failed');
      process.exit(1);
    }
  }

  // Exit with appropriate status code based on husky install status
  if (huskyInstallStatus === 0) {
    console.log('Husky preparation executed successfully!');
    process.exit(0);
  } else {
    console.error('Husky installation failed');
    process.exit(1);
  }
};

prepareHusky()
```

> NOTE: As this PR has changes that are involved in the contribution flow we also need to update the Contribution guide according to this new convention of commit messages.

Ok, Sure I will add all necessary docs.

2023-07-20 18:06 UTC, wajeshubham commented
@balaji-sivasakthi script is failing in the macOS on running `yarn prepare`

```bash
# Error:
husky - Git hooks installed
chmod: .husky/*: No such file or directory # I have .husky folder. Testing your branch only
Setting permissions failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Also, seems like an extra boilerplate to just lint the commit, which no doubt is a good practice. However, it would be great if we consider and test all the edge cases before merging.

Thank you! 😀

2023-07-21 04:07 UTC, balaji-sivasakthi commented
@wajeshubham 

```
# Error:
husky - Git hooks installed
chmod: .husky/*: No such file or directory # I have .husky folder. Testing your branch only
Setting permissions failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I've tested it in **GitHub Codespace**, and it works well now.

2023-07-21 04:33 UTC, balaji-sivasakthi commented
@wajeshubham I'm also updated README.md and CONTRIBUTOR.md for conventional commit message format. Please take a moment to look at this.

2023-07-21 07:12 UTC, jwala-anirudh commented
@balaji-sivasakthi thanks for the PR, I will review it thoroughly and provide the approval

2023-07-22 16:43 UTC, balaji-sivasakthi commented
@wajeshubham Is this ok?

2023-07-22 16:52 UTC, wajeshubham commented
Yes @balaji-sivasakthi we are reviewing it.

2023-07-30 09:18 UTC, jwala-anirudh requested changes
I have added some comments after reviewing the changes, please go through them

2023-07-30 14:44 UTC, balaji-sivasakthi commented on .husky/pre-commit
> +npx lint-staged --allow-empty
It was correctly configured in `.lintstagedrc`, also I installed `lint-staged` with devDependencies
```json
  "devDependencies": {
    "@commitlint/cli": "^17.6.6",
    "@commitlint/config-conventional": "^17.6.5",
    "husky": "^8.0.3",
    "lint-staged": "^13.2.2",
    "nodemon": "^2.0.22",
    "prettier": "^3.0.0"
  }
```

2023-07-30 14:47 UTC, balaji-sivasakthi commented on CONTRIBUTING.md
> +4. Make your changes and commit them with descriptive messages: `git commit -am 'add your commit message'`. ([Commit format guidelines](#commit-message-format))
This has been resolved. Please check now.

2023-07-30 14:54 UTC, balaji-sivasakthi commented on prepare.js
> +    fs.mkdirSync(".husky");
I added `fs.mkdir()` asynchronously with proper error handling, which would also be a good alternative to `mkdirSync`, as it won't block the event loop and can handle errors more gracefully.

2023-07-30 14:54 UTC, balaji-sivasakthi commented
@jwala-anirudh Please check the recent changes

2023-07-30 15:09 UTC, jwala-anirudh approved these changes
Approved.

2023-07-31 10:36 UTC, wajeshubham approved these changes

2023-08-02 09:06 UTC, wajeshubham approved these changes
Looks good!

2023-08-02 09:09 UTC, merged