update new refresh token in the db
hiteshchoudhary/apihub pull request #201
Opened 2024-10-01 12:30 UTC by suryo811

New refresh token was not being updated in the users db when the refreshAccessToken method was called in auth Controller.

2024-10-02 08:50 UTC, wajeshubham requested changes

2024-10-02 08:50 UTC, wajeshubham commented on src/controllers/apps/auth/user.controllers.js
> -        user.loginType?.toLowerCase() +
Please remove these formatting changes

2024-10-19 17:33 UTC, wajeshubham approved these changes

2024-10-19 17:33 UTC, merged

2024-10-20 06:57 UTC, Ashutosh257 commented
Hi @wajeshubham @suryo811 isn't this code handled on line 27 in `generateAccessAndRefreshTokens` function? Or am I wrong?

2024-10-20 07:23 UTC, suryo811 commented
Yes, @Ashutosh257  it is already being handled in `generateAccessAndRefreshTokens` . (Thanks for pointing out).  Should the function `generateAccessAndRefreshTokens` focus solely on generating the tokens, while the logic to store refresh token on db be handled in controller itself ? @wajeshubham