feat: added todo web frontend
hiteshchoudhary/apihub pull request #60
Opened 2023-10-08 05:20 UTC by Rudra-Patel-code

created a frontend part of todo app, using vite and typescript in react and tailwind css

2023-10-08 05:21 UTC, Rudra-Patel-code commented
Do let me know if there are changes to be done

2023-12-13 09:46 UTC, wajeshubham requested changes
The UI is not up to the mark. It would be great if you could take a look at the following UI for the todo app. Please redesign the todo app based on the provided UI.

Todo app UI: https://devuiv2.vercel.app/templates/todo (Take a look at the other application screens for input and button components.)

2023-12-13 09:46 UTC, wajeshubham commented on examples/todo-app/web/README.md
> +# React + TypeScript + Vite
Update the `README.md` with correct instruction on how to do the setup and installation including env file configuration

2023-12-13 09:46 UTC, wajeshubham commented on examples/todo-app/web/index.html
> +    <title>Vite + React + TS</title>
Update the title based on the application

2024-01-13 15:39 UTC, closed without merging