Feat/logger
hiteshchoudhary/apihub pull request #80
Opened 2024-02-07 17:46 UTC by tarun-kavipurapu

Under Logger Folder
Created a logger for Applications Errors with Winston and for logging http call using Morgon 

Since the output format and the method was not mentioned used custom format and displayed the output to the Console

Happy to make any changes if further infromation is provided by the maintainers

Demo image which shows both application error and http log
![image](https://github.com/hiteshchoudhary/apihub/assets/35888688/275cb038-9175-4802-b9aa-d27a3b905e00)

2024-02-07 18:40 UTC, wajeshubham requested changes
Please **take a pull of** the changes to your local branch and resolve the reviewed changes. I have refactored file structure and `morgan` and `winston` logger configurations. **Make sure you test the logging thoroughly before requesting a review.**

Thanks!

2024-02-07 18:40 UTC, wajeshubham commented on src/logger/winston/index.js
No need for this file. We don't want the logger in the development mode only we also want this in production. This `NODE_ENV` check is unnecessary. This will break the application in production. So remove this file.

2024-02-07 18:40 UTC, wajeshubham commented on src/logger/winston/dev.logger.js
No need to add folders for `morgan` and `winston` as there are no more than one files in the each folder. So, keep `logger/` folder and inside it morgan and winston logger files. rename this file from `dev.logger.js` to `winston.logger.js` and rename `devLogger` variable to just `logger`.

2024-02-07 18:40 UTC, wajeshubham commented on src/app.js
> +app.use(morganMiddleWare);
inject this middleware at the end of all the middlewares. After `app.use(passport.session());` to be precise.

2024-02-07 18:40 UTC, wajeshubham commented on src/logger/morgan/morgon.logger.js
> +    skip: (req, res) => res.statusCode < 400,
Log all the api logs do not skip success responses. I think you can remove this `skip` key.

2024-02-07 18:40 UTC, wajeshubham commented on package-lock.json
Remove this file and user `yarn` instead of `npm`. Also, fix `yarn.lock` file changes by removing package locka dn reinstalling the packages using yarn.

2024-02-07 18:40 UTC, wajeshubham commented on yarn.lock
Remove `package-lock.json` and reinstall packages using `yarn`

2024-02-08 04:57 UTC, tarun-kavipurapu commented
Successfully Implemented the mentioned changes 
Application Error log and http log
![Screenshot from 2024-02-08 10-20-30](https://github.com/hiteshchoudhary/apihub/assets/35888688/409c9045-2f17-4819-ae16-c6e598c014b6)

apologize for previous mistakes as this was my first time contributing

2024-02-08 10:22 UTC, wajeshubham approved these changes
LGTM!

2024-02-08 10:22 UTC, merged