Feat/status codes
hiteshchoudhary/apihub pull request #91
Opened 2024-02-24 15:02 UTC by atulbhatt-system32

- Setup Basic Project Structure
- Added Home Page/Landing Page

2024-03-17 06:21 UTC, wajeshubham commented
@atulbhatt-system32 any update on this? Kindly let us know.

2024-03-30 15:16 UTC, atulbhatt-system32 commented
@wajeshubham ready for Review

2024-04-02 19:56 UTC, wajeshubham requested changes
Kindly go through the review comments and it would be great if we have some demo video of the application.

Thanks

2024-04-02 19:56 UTC, wajeshubham commented on package-lock.json
We are using `yarn`. Please read `README.md` and `CONTRIBUTING.md` file carefully before starting the contribution. Please use yarn for package installation. Also, this is a frontend contribution this must not affect core freeapi code files. So, addition of `package-lock.json` is irrelevant here.

2024-04-02 19:56 UTC, wajeshubham commented on package.json
This file must not be updated as this is a frontend contribution and this package.json belongs to the core freeapi project.,

2024-04-03 10:02 UTC, atulbhatt-system32 commented on package-lock.json
Hey @wajeshubham thanks for the feedback. I actually read the contributing.md but my bad I did this blunders even then. Sure, I will go through the contributing.md once more and make necessary updates.

2024-04-03 10:03 UTC, atulbhatt-system32 commented
> Kindly go through the review comments and it would be great if we have some demo video of the application.
> 
> Thanks

Definitely will include a video too.

2024-04-06 12:32 UTC, wajeshubham commented
@atulbhatt-system32 Is this PR ready for review? I can still see the `package-lock.json` file in the commit. Also, when can we expect quiz part for this app as we would like to include all these features in a single PR. Let us know the timeline.

Thank you

2024-04-06 14:03 UTC, atulbhatt-system32 commented
@wajeshubham by Next weekend I will add the quiz part too. Tomorrow I will plan on some quiz layout.

2024-04-07 07:24 UTC, wajeshubham commented
Ok, if that's the case then we can wait till you finish the quiz app and after the changes are done, I'll review and merge the code. Thanks!

2024-04-17 19:15 UTC, wajeshubham commented
@atulbhatt-system32 Any update on this?

2024-04-20 12:10 UTC, atulbhatt-system32 commented
> @atulbhatt-system32 Any update on this?

@wajeshubham updated just now. Also attached a video for the quiz page.

2024-04-25 18:37 UTC, wajeshubham approved these changes

2024-04-25 18:37 UTC, merged